package Design_Patterns.CreationalPattern.singleton;
//In Java, a hash code is an integer value associated with every object, which is generated by a hashing algorithm1.
//This hash code is used in data structures like hash tables (for example, HashMap and HashSet) to efficiently store and access data
//Whenever it is invoked on the same object more than once during an execution of a Java application, hashCode() must consistently return the same value


public class MainSingleton {
    public static void main(String[] args) {

        //int               a
        SingletonLazyMethod sl1 = SingletonLazyMethod.getSingletonLazy();//static method called by classname.methodname
        System.out.println("Object 1 hash code = "+sl1.hashCode());

        SingletonLazyMethod sl2 = SingletonLazyMethod.getSingletonLazy();
        System.out.println("Object 2 hash code = "+sl2.hashCode());

        SingletonEarlyMethod se1 = SingletonEarlyMethod.getSingletonEarly();
        System.out.println("Early Object 1 hash code = "+se1.hashCode());

        SingletonEarlyMethod se2 = SingletonEarlyMethod.getSingletonEarly();
        System.out.println("Early Object 2 hash code = "+se2.hashCode());

        SingletonThreads st1 = SingletonThreads.getSingletonT();
        System.out.println("Lazy synchronized object 1 hash code = "+st1.hashCode());

        SingletonThreads st2 = SingletonThreads.getSingletonT();
        System.out.println("Lazy Synchronized object 2 hash code = "+st2.hashCode());
    }
}
